var htmlBuilder = "";

var header = ["Teams", "Wins", "Losses"];
var teams = ["Braves", "Nationals", "Phillies", "Mets", "Marlins", "Cardinals", "Cubs", "Brewers", "Reds", "Pirates", "Dodgers", "Diamondbacks", "Giants", "Padres", "Rockies"];
var wins = [89, 79, 74, 72, 51, 81, 76, 74, 67, 62, 93, 75, 69, 66, 60];
var losses = [55, 63, 68, 70, 91, 62, 66, 68, 77, 81, 52, 68, 74, 76, 84];

var tempHighWins = 0;
var tempLeader = 0;

for (var i = 0; i < teams.length; i++) {
    if (wins[i] >= tempHighWins) {
        tempHighWins = wins[i];
        tempLeader = i;
    }
}

// Create HTML table with borders (borders generated by chatgpt)
htmlBuilder += "<table border='1' cellpadding='5' cellspacing='0'>";
htmlBuilder += "<tr>";
header.forEach(function(item) {
    htmlBuilder += "<th>" + item + "</th>";
});
htmlBuilder += "</tr>";

for (var i = 0; i < teams.length; i++) {
    var rowStyle = (i === tempLeader) ? "font-weight: bold;" : ""; //I could not get <strong> to work
    htmlBuilder += "<tr style='" + rowStyle + "'>";
    htmlBuilder += "<td>" + teams[i] + "</td>";
    htmlBuilder += "<td>" + wins[i] + "</td>";
    htmlBuilder += "<td>" + losses[i] + "</td>";
    htmlBuilder += "</tr>";
}

htmlBuilder += "</table>";

document.getElementById('teams').innerHTML = htmlBuilder;



